document.write("<!DOCTYPE HTML PUBLIC \"-\/\/W3C\/\/DTD HTML 4.01 Transitional\/\/EN\">");
document.write("");
document.write("<html>");
document.write("");
document.write("<head>");
document.write("<title>citations<\/title>");
document.write("<\/head>");
document.write("");
document.write("<body>");
document.write("");
document.write("<!-- This document was automatically generated with bibtex2html 1.98");
document.write("     (see http:\/\/www.lri.fr\/~filliatr\/bibtex2html\/),");
document.write("     with the following command:");
document.write("     .\/bibtex2html ..\/citations.bib  -->");
document.write("");
document.write("");
document.write("<table>");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"chakrabortypga\">1<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Rudrasis Chakraborty, Dohyung Seo and Baba&nbsp;C Vemuri.");
document.write(" An efficient Exact-PGA algorithm for constant curvature manifolds");
document.write(" <em>CVPR (accepted)<\/em>, 2016.");
document.write("[&nbsp;<a href=\"citations_bib.html#chakrabortypga\">bib<\/a>&nbsp;]");
document.write("[&nbsp;<a href=\"exact_PGA.zip\">codes<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"chakrabortygrassmann\">2<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Rudrasis Chakraborty and Baba&nbsp;C Vemuri.");
document.write(" Recursive frechet mean computation on the grassmann and its");
document.write("  applications to computer vision.");
document.write(" <em>ICCV (accepted)<\/em>, 2015.");
document.write("[&nbsp;<a href=\"citations_bib.html#chakrabortygrassmann\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"salehian2015efficient\">3<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Hesamoddin Salehian, Rudrasis Chakraborty, Edward Ofori, David Vaillancourt,");
document.write("  and Baba&nbsp;C Vemuri.");
document.write(" An efficient recursive estimator of the fr&eacute;chet mean on a");
document.write("  hypersphere with applications to medical image analysis.");
document.write(" <em>MICCAI sponsored workshop MFCA<\/em>, 2015.");
document.write("[&nbsp;<a href=\"citations_bib.html#salehian2015efficient\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"chakrabortyefficient\">4<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Rudrasis Chakraborty, Monami Banerjee, Dohyung Seo, Sara Turner, David Fuller,");
document.write("  John Forder, and Baba&nbsp;C Vemuri.");
document.write(" An efficient recursive algorithm for atlas construction.");
document.write(" <em>MICCAI sponsored workshop MFCA<\/em>, 2015.");
document.write("[&nbsp;<a href=\"citations_bib.html#chakrabortyefficient\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"banerjeeregression\">5<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Monami Banerjee, Rudrasis Chakraborty, Edward Ofori, David Vaillancourt, and");
document.write("  Baba&nbsp;C Vemuri.");
document.write(" Nonlinear regression on riemannian manifolds and its applications to");
document.write("  neuro-image analysis.");
document.write(" <em>MICCAI (accepted)<\/em>, 2015.");
document.write("[&nbsp;<a href=\"citations_bib.html#banerjeeregression\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"ghosal2009speech\">6<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Arijit Ghosal, Rudrasis Chakraborty, S&nbsp;Haty, BC&nbsp;Dhara, and Samar&nbsp;K Saha.");
document.write(" Speech\/music classification using occurrence pattern of zcr and ste.");
document.write(" In <em>Intelligent Information Technology Application, 2009. IITA");
document.write("  2009. Third International Symposium on<\/em>, volume&nbsp;3, pages 435--438. IEEE,");
document.write("  2009.");
document.write("[&nbsp;<a href=\"citations_bib.html#ghosal2009speech\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"ghosal2011instrumental\">7<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Arijit Ghosal, Rudrasis Chakraborty, Bibhas&nbsp;Chandra Dhara, and Sanjoy&nbsp;Kumar");
document.write("  Saha.");
document.write(" Instrumental\/song classification of music signal using ransac.");
document.write(" In <em>Electronics Computer Technology (ICECT), 2011 3rd");
document.write("  International Conference on<\/em>, volume&nbsp;1, pages 269--272. IEEE, 2011.");
document.write("[&nbsp;<a href=\"citations_bib.html#ghosal2011instrumental\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"ghosal2011song\">8<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Arijit Ghosal, Rudrasis Chakraborty, Bibhas&nbsp;Chandra Dhara, and Sanjoy&nbsp;Kumar");
document.write("  Saha.");
document.write(" Song classification: Classical and non-classical discrimination using");
document.write("  mfcc co-occurrence based features.");
document.write(" In <em>Signal Processing, Image Processing and Pattern Recognition<\/em>,");
document.write("  pages 179--185. Springer Berlin Heidelberg, 2011.");
document.write("[&nbsp;<a href=\"citations_bib.html#ghosal2011song\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"ghosal2012music\">9<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Arijit Ghosal, Rudrasis Chakraborty, Bibhas&nbsp;Chandra Dhara, and Sanjoy&nbsp;Kumar");
document.write("  Saha.");
document.write(" Music classification based on mfcc variants and amplitude variation");
document.write("  pattern: a hierarchical approach.");
document.write(" <em>International Journal of Signal Processing, Image Processing and");
document.write("  Pattern Recognition<\/em>, 5(1):131--150, 2012.");
document.write("[&nbsp;<a href=\"citations_bib.html#ghosal2012music\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"srinivasan2012segmenting\">10<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Sriram Srinivasan, Sourangshu Bhattacharya, and Rudrasis Chakraborty.");
document.write(" Segmenting web-domains and hashtags using length specific models.");
document.write(" In <em>Proceedings of the 21st ACM international conference on");
document.write("  Information and knowledge management<\/em>, pages 1113--1122. ACM, 2012.");
document.write("[&nbsp;<a href=\"citations_bib.html#srinivasan2012segmenting\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"bandyopadhyay2013incorporating\">11<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Sanghamitra Bandyopadhyay, Ujjwal Maulik, and Rudrasis Chakraborty.");
document.write(" Incorporating ϵ-dominance in amosa: Application to multiobjective");
document.write("  0\/1 knapsack problem and clustering gene expression data.");
document.write(" <em>Applied Soft Computing<\/em>, 13(5):2405--2411, 2013.");
document.write("[&nbsp;<a href=\"citations_bib.html#bandyopadhyay2013incorporating\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"ghosal2012song\">12<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Arijit Ghosal, Rudrasis Chakraborty, Bibhas&nbsp;Chandra Dhara, and Sanjoy&nbsp;Kumar");
document.write("  Saha.");
document.write(" Song\/instrumental classification using spectrogram based contextual");
document.write("  features.");
document.write(" In <em>Proceedings of the CUBE International Information Technology");
document.write("  Conference<\/em>, pages 21--25. ACM, 2012.");
document.write("[&nbsp;<a href=\"citations_bib.html#ghosal2012song\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"ghosal2011automatic\">13<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Arijit Ghosal, Rudrasis Chakraborty, Bibhas&nbsp;Chandra Dhara, and Sanjoy&nbsp;Kumar");
document.write("  Saha.");
document.write(" Automatic identification of instrument type in music signal using");
document.write("  wavelet and mfcc.");
document.write(" In <em>Computer Networks and Intelligent Computing<\/em>, pages 560--565.");
document.write("  Springer Berlin Heidelberg, 2011.");
document.write("[&nbsp;<a href=\"citations_bib.html#ghosal2011automatic\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"ghosal2013hierarchical\">14<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Arijit Ghosal, Rudrasis Chakraborty, Bibhas&nbsp;Chandra Dhara, and Sanjoy&nbsp;Kumar");
document.write("  Saha.");
document.write(" A hierarchical approach for speech-instrumental-song classification.");
document.write(" <em>SpringerPlus<\/em>, 2(1):1--11, 2013.");
document.write("[&nbsp;<a href=\"citations_bib.html#ghosal2013hierarchical\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"ghosal2014genre\">15<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Arijit Ghosal, Rudrasis Chakraborty, Bibhas&nbsp;Chandra Dhara, and Sanjoy&nbsp;Kumar");
document.write("  Saha.");
document.write(" Genre-based classification of song using perceptual features.");
document.write(" In <em>Intelligent Computing, Networking, and Informatics<\/em>, pages");
document.write("  267--276. Springer India, 2014.");
document.write("[&nbsp;<a href=\"citations_bib.html#ghosal2014genre\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"chakraborty2014sensor\">16<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Rudrasis Chakraborty, Chin-Teng Lin, and Nikhil&nbsp;R Pal.");
document.write(" Sensor (group feature) selection with controlled redundancy in a");
document.write("  connectionist framework.");
document.write(" <em>International journal of neural systems<\/em>, 24(06):1450021, 2014.");
document.write("[&nbsp;<a href=\"citations_bib.html#chakraborty2014sensor\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"chakraborty2015feature\">17<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Rudrasis Chakraborty and Nikhil&nbsp;R Pal.");
document.write(" Feature selection using a neural framework with controlled");
document.write("  redundancy.");
document.write(" <em>Neural Networks and Learning Systems, IEEE Transactions on<\/em>,");
document.write("  26(1):35--50, 2015.");
document.write("[&nbsp;<a href=\"citations_bib.html#chakraborty2015feature\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"chakraborty2012incorporating\">18<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Rudrasis Chakraborty.");
document.write(" <em>Incorporating epsilon-dominance in MultiObjective Optimization:");
document.write("  A Study in AMOSA<\/em>.");
document.write(" Master's thesis, Indian Statistical Institution, 2012.");
document.write("[&nbsp;<a href=\"citations_bib.html#chakraborty2012incorporating\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"bandyopadhyay2015priority\">19<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Sanghamitra Bandyopadhyay, Rudrasis Chakraborty, and Ujjwal Maulik.");
document.write(" Priority based∊ dominance: A new measure in multiobjective");
document.write("  optimization.");
document.write(" <em>Information Sciences<\/em>, 305:97--109, 2015.");
document.write("[&nbsp;<a href=\"citations_bib.html#bandyopadhyay2015priority\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("");
document.write("");
document.write("<tr valign=\"top\">");
document.write("<td align=\"right\" class=\"bibtexnumber\">");
document.write("[<a name=\"ghosal2015perceptual\">20<\/a>]");
document.write("<\/td>");
document.write("<td class=\"bibtexitem\">");
document.write("Arijit Ghosal, Rudrasis Chakraborty, Bibhas&nbsp;Chandra Dhara, and Sanjoy&nbsp;Kumar");
document.write("  Saha.");
document.write(" Perceptual feature-based song genre classification using ransac.");
document.write(" <em>International Journal of Computational Intelligence Studies<\/em>,");
document.write("  4(1):31--49, 2015.");
document.write("[&nbsp;<a href=\"citations_bib.html#ghosal2015perceptual\">bib<\/a>&nbsp;]");
document.write("");
document.write("<\/td>");
document.write("<\/tr>");
document.write("<\/table><hr><p><em>This file was generated by");
document.write("<a href=\"http:\/\/www.lri.fr\/~filliatr\/bibtex2html\/\">bibtex2html<\/a> 1.98.<\/em><\/p>");
document.write("<\/body>");
document.write("<\/html>");
document.write("");

